""" Migration file"""
from django.db import migrations, models

# Generated by Django 3.2 on 2022-01-28 23:06


class Migration(migrations.Migration):
    ''' Creating Migration class.'''

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
